### PR TITLE
Support `trailing` and `leading` horizontal alignment

### PR DESCRIPTION
**Pull request by e-sung**
Hi! This flow layout is really well written and was easy to understand.
And I think it would be great if this layout swaps horizontal alignment for Right-to-Left language users.
Thus this PR.

Thank you for making this nice code open source!

### CODE REVIEW

**Comment by mischa-hildebrand** [comment]
Looks like a great suggestion! 
Thanks for creating the pull request! I'll look over it in a couple of days when the conference is over... 😉

**Comment by mischa-hildebrand** [comment]
Hey @e-sung,
I like your suggestion to add `.leading` and `.trailing` to the `HorizontalAlignment` enum and your idea how to implement it. However, I would like to make the code a little more expressive. So I modified your code and created a [pull request on your `master` branch](https://github.com/e-sung/AlignedCollectionViewFlowLayout/pull/1).
Would be great if you could review and merge it if you're fine with it, so I can finally integrate it into the this repository.
Thx!

**Comment by e-sung** [comment]
Hi! I looked through your code and merged it. It seems much better!

**Comment by mischa-hildebrand** [comment]
Awesome. Thanks again for contributing this great idea! 👍 I've merged it into the main branch.

**Pull request merged**
